### ISSUE TITLE
Better PHP support

### ISSUE THREAD

**Issue by patrick91** [bernatfortet/sublime-frontend-delight#4]
Can you please change the color of the function calls?

![screen shot 2013-06-03 at 8 49 35 am](https://f.cloud.github.com/assets/667029/597964/dad5dcc6-cc19-11e2-983d-cf8a9f67f09d.png)

**Comment by bernatfortet** [comment]
Hey Patrick I have done a first iteration. Feel free to modify it, or give me more feedback.
I usually don't work with PHP

https://github.com/bernatfortet/sublime-frontend-delight/commit/74daccd934341d0c0e29bfc3ba4bf57c925037cb

**Comment by patrick91** [comment]
You're lucky ^^

Many thanks, it looks great now! :)
